// utils/user-profile.js

export function getBlankUserProfile({ user, userRole = "student", schoolIdVal = "" }) {
  return {
    name: user.displayName || "",
    dob: "",
    profilePicUrl: "",
    cdlClass: "",
    endorsements: [],
    restrictions: [],
    experience: "",
    prevEmployer: "",
    assignedCompany: "",
    assignedInstructor: "",
    cdlPermit: "",
    permitPhotoUrl: "",
    permitExpiry: "",
    driverLicenseUrl: "",
    licenseExpiry: "",
    medicalCardUrl: "",
    medCardExpiry: "",
    vehicleQualified: "",
    truckPlateUrl: "",
    trailerPlateUrl: "",
    emergencyName: "",
    emergencyPhone: "",
    emergencyRelation: "",
    waiverSigned: false,
    waiverSignature: "",
    course: "",
    schedulePref: "",
    scheduleNotes: "",
    paymentStatus: "",
    paymentProofUrl: "",
    accommodation: "",
    studentNotes: "",
    profileProgress: 0,
    profileUpdatedAt: null,
    lastUpdatedBy: "",
    email: user.email,
    role: userRole,
    schoolId: schoolIdVal,
    createdAt: new Date().toISOString(),
    uid: user.uid || "",
  };
}